languageCode: en
title: Protocol Labs Research
summaryLength: 30
googleAnalytics: UA-96910779-16
BaseURL: "https://research.protocol.ai"
relativeURLs: true
copyright: "© Protocol Labs, Inc. Except as noted, content licensed CC-BY 3.0."
taxonomies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags
  area: areas
  group: groups
params:
  DateForm: 2006.1.2
  Avatar: /images/pl_research_card.png
  Logo: /images/pl_research_logo.svg
  Author: "Protocol Labs Research"
  Description: "Protocol Labs Research explores the future of decentralization and examines the infrastructure limiting what you can do with technology."
  Locale: "en_US"
  TwitterUser: "@protocollabs"
permalinks:
  talks: /talks/:title/
  publications: /publications/:title/
  areas: /areas/:title/
  groups: /groups/:title/
  posts: /blog/:year/:title/
markup:
  goldmark:
    renderer:
      unsafe: true
