languageCode: en-us
title: Protocol Labs Research
summaryLength: 30
googleAnalytics: UA-96910779-16
relativeURLs: true
taxonomies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags
  research-area: research-areas
  research-group: research-groups
BaseURL: "https://research.protocol.ai"
params:
  DateForm: 2006.1.2
  BaseURL: "https://research.protocol.ai"
  Avatar: /images/pl_research_logo.png
permalinks:
  talks: /research/talks/:title/
  publications: /research/publications/:title/
