version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - checkout

      - run:
          name: "Install Hugo"
          command: curl -sL -o/tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.69.2/hugo_0.69.2_Linux-64bit.deb && sudo dpkg -i /tmp/hugo.deb

      - run:
          name: "Install dependencies"
          command: yarn

      - run:
          name: "Build project"
          command: yarn run build

      - persist_to_workspace:
          root: ~/hugo/
          paths:
            - public

  deploy:
    docker:
      - image: olizilla/ipfs-dns-deploy:latest
        environment:
          DOMAIN: research.protocol.ai
          BUILD_DIR: public
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy website to IPFS
          command: |
            pin_name="$DOMAIN build $CIRCLE_BUILD_NUMBER"

            hash=$(pin-to-cluster.sh "$pin_name" /tmp/workspace/$BUILD_DIR)

            echo "Website added to IPFS: https://ipfs.io/ipfs/$hash"

            if [ "$CIRCLE_BRANCH" == "master" ] ; then
              dnslink-dnsimple -d $DOMAIN -r _dnslink -l /ipfs/$hash
            fi

  # This is a terrible hack, but since ~ May 2020 it's often necessary to deploy twice for things to work
  # Should be properly debugged at some point but we can't have the website go offline with each commit
  redeploy:
    docker:
      - image: olizilla/ipfs-dns-deploy:latest
        environment:
          DOMAIN: research.protocol.ai
          BUILD_DIR: public
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Re-deploy website to IPFS
          command: |
            pin_name="$DOMAIN build $CIRCLE_BUILD_NUMBER-2"
            hash=$(pin-to-cluster.sh "$pin_name" /tmp/workspace/$BUILD_DIR)
            dnslink-dnsimple -d $DOMAIN -r _dnslink -l /ipfs/$hash

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          context: ipfs-dns-deploy
          requires:
            - build
      - redeploy:
          context: ipfs-dns-deploy
          filters:
            branches:
              only: master    
          requires:
            - deploy
