name: Check for internal links

on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    name: Scan
    steps:
    - name: Scan for research.protocol.ai occurrences
      uses: jsoares/gh-pr-content-checker@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        diffDoesNotContain: 'research.protocol.ai'
